export const RuAbc = [
    [
        { value: "ё" , className: '' },
        { value: "1" , className: '' },
        { value: "2" , className: '' },
        { value: "3" , className: '' },
        { value: "4" , className: '' },
        { value: "5" , className: '' },
        { value: "6" , className: '' },
        { value: "7" , className: '' },
        { value: "8" , className: '' },
        { value: "9" , className: '' },
        { value: "0" , className: '' },
        { value: "-" , className: '' },
        { value: "=" , className: '' },
        { value: "Backspace" , className: 'backspace' },
    ],
    [
        { value: "Tab" , className: 'tab' },
        { value: "й" , className: '' },
        { value: "ц" , className: '' },
        { value: "у" , className: '' },
        { value: "к" , className: '' },
        { value: "е" , className: '' },
        { value: "н" , className: '' },
        { value: "г" , className: '' },
        { value: "ш" , className: '' },
        { value: "щ" , className: '' },
        { value: "з" , className: '' },
        { value: "х" , className: '' },
        { value: "ъ" , className: '' },
        { value: "Del" , className: 'del' },
    ],
    [
        { value: "Caps Lock" , className: 'caps_lock' },
        { value: "ф" , className: '' },
        { value: "ы" , className: '' },
        { value: "в" , className: '' },
        { value: "а" , className: '' },
        { value: "п" , className: '' },
        { value: "р" , className: '' },
        { value: "о" , className: '' },
        { value: "л" , className: '' },
        { value: "д" , className: '' },
        { value: "ж" , className: '' },
        { value: "э" , className: '' },
        { value: "Enter" , className: 'enter' },      
    ],
    [
        { value: "Shift" , className: 'shift' },
        { value: "я" , className: '' },
        { value: "ч" , className: '' },
        { value: "с" , className: '' },
        { value: "м" , className: '' },
        { value: "и" , className: '' },
        { value: "т" , className: '' },
        { value: "ь" , className: '' },
        { value: "б" , className: '' },
        { value: "ю" , className: '' },
        { value: "." , className: '' },
        { value: "↑" , className: 'page_up' },
        { value: "Shift" , className: '' },
    ],
    [
        { value: "Ctrl" , className: 'ctrl' }, 
        { value: "Win" , className: 'win' },
        { value: "Alt" , className: 'alt' },
        { value: "Space" , className: 'space' },
        { value: "Alt" , className: 'alt' },
        { value: "Ctrl" , className: 'ctrl' },
        { value: "←" , className: 'page_left' },
        { value: "↓" , className: 'page_down' },
        { value: "→" , className: 'page_right' },
    ]
];

export const Abc = [
    [
        { value: "`" , className: '' },
        { value: "1" , className: '' },
        { value: "2" , className: '' },
        { value: "3" , className: '' },
        { value: "4" , className: '' },
        { value: "5" , className: '' },
        { value: "6" , className: '' },
        { value: "7" , className: '' },
        { value: "8" , className: '' },
        { value: "9" , className: '' },
        { value: "0" , className: '' },
        { value: "-" , className: '' },
        { value: "=" , className: '' },
        { value: "Backspace" , className: 'backspace' },
    ],
    [
        { value: "Tab" , className: 'tab' },
        { value: "q" , className: '' },
        { value: "w" , className: '' },
        { value: "e" , className: '' },
        { value: "r" , className: '' },
        { value: "t" , className: '' },
        { value: "y" , className: '' },
        { value: "u" , className: '' },
        { value: "i" , className: '' },
        { value: "o" , className: '' },
        { value: "p" , className: '' },
        { value: "[" , className: '' },
        { value: "]" , className: '' },
        { value: "Del" , className: 'del' },
    ],
    [
        { value: "Caps Lock" , className: 'caps_lock' },
        { value: "a" , className: '' },
        { value: "s" , className: '' },
        { value: "d" , className: '' },
        { value: "f" , className: '' },
        { value: "g" , className: '' },
        { value: "h" , className: '' },
        { value: "j" , className: '' },
        { value: "k" , className: '' },
        { value: "l" , className: '' },
        { value: ";" , className: '' },
        { value: "'" , className: '' },
        { value: "Enter" , className: 'enter' },      
    ],
    [
        { value: "Shift" , className: 'shift' },
        { value: "z" , className: '' },
        { value: "x" , className: '' },
        { value: "c" , className: '' },
        { value: "v" , className: '' },
        { value: "b" , className: '' },
        { value: "n" , className: '' },
        { value: "m" , className: '' },
        { value: "," , className: '' },
        { value: "." , className: '' },
        { value: "/" , className: '' },
        { value: "↑" , className: 'page_up' },
        { value: "Shift" , className: '' },
    ],
    [
        { value: "Ctrl" , className: 'ctrl' }, 
        { value: "Win" , className: 'win' },
        { value: "Alt" , className: 'alt' },
        { value: "Space" , className: 'space' },
        { value: "Alt" , className: 'alt' },
        { value: "Ctrl" , className: 'ctrl' },
        { value: "←" , className: 'page_left' },
        { value: "↓" , className: 'page_down' },
        { value: "→" , className: 'page_right' },
    ]
]